# Generated by Django 5.0.6 on 2024-07-01 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PokemonCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_name",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="卡片名稱"
                    ),
                ),
                (
                    "evolve_marker",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="進化類別"
                    ),
                ),
                (
                    "card_hp",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="卡片血量"
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="屬性"
                    ),
                ),
                (
                    "Weakness",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="弱點"
                    ),
                ),
                (
                    "Resistance",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="抵抗"
                    ),
                ),
                (
                    "Escape",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="撤退"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="說明"),
                ),
                (
                    "card_alpha",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="發行盒號"
                    ),
                ),
                (
                    "card_rule",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="卡標"
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="編號"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PokemonCardSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_type", models.CharField(max_length=10, verbose_name="種類")),
                ("skill_name", models.CharField(max_length=100, verbose_name="名稱")),
                ("sikll_Cost", models.CharField(max_length=100, verbose_name="能量")),
                ("sikll_Damnage", models.CharField(max_length=100, verbose_name="傷害")),
                ("sikll_Effect", models.CharField(max_length=100, verbose_name="特效")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="CardInfo.pokemoncard",
                        verbose_name="卡片",
                    ),
                ),
            ],
        ),
    ]
