# Generated by Django 5.0.6 on 2024-07-01 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CardInfo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemoncardskill",
            old_name="sikll_Cost",
            new_name="skill_cost",
        ),
        migrations.RenameField(
            model_name="pokemoncardskill",
            old_name="sikll_Damnage",
            new_name="skill_damnage",
        ),
        migrations.RenameField(
            model_name="pokemoncardskill",
            old_name="sikll_Effect",
            new_name="skill_effect",
        ),
    ]
