# Generated by Django 5.0.6 on 2024-07-01 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("CardInfo", "0002_rename_sikll_cost_pokemoncardskill_skill_cost_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemoncardskill",
            old_name="skill_damnage",
            new_name="skill_damage",
        ),
    ]
