# Generated by Django 5.0.6 on 2024-07-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CardInfo", "0004_alter_pokemoncardskill_skill_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemoncard",
            name="web_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="路徑id"
            ),
        ),
        migrations.AddField(
            model_name="pokemoncard",
            name="web_url",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="路徑"
            ),
        ),
    ]
