# Generated by Django 5.0.6 on 2024-07-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CardInfo", "0005_pokemoncard_web_id_pokemoncard_web_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemoncard",
            name="card_alpha",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="發行盒號"
            ),
        ),
        migrations.AlterField(
            model_name="pokemoncard",
            name="card_number",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="編號"
            ),
        ),
        migrations.AlterField(
            model_name="pokemoncard",
            name="card_rule",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="卡標"
            ),
        ),
    ]
