# Generated by Django 5.0.6 on 2024-07-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CardInfo", "0006_alter_pokemoncard_card_alpha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemoncardskill",
            name="skill_effect",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="特效"
            ),
        ),
    ]
